const ANDONG_DATA = {
  i18n: {
    en: {
      siteTitle: "ANDONG GUIDE",
      siteSubtitle: "KOREA",
      heroTitle: "Explore Andong, Spirit of Korea",
      heroDesc: "Your complete interactive companion to UNESCO World Heritage sites, rich Joseon traditions, and legendary local cuisine.",
      searchPlaceholder: "Search attractions (e.g., Hahoe Village, Jjimdak, Moonlight Bridge)...",
      searchBtn: "Search",
      filterAll: "All Spots",
      filterHeritage: "UNESCO Heritage",
      filterNight: "Night Views",
      filterKdrama: "K-Drama Spots",
      filterNature: "Nature & Parks",
      tabAttractions: "Attractions",
      tabFood: "Cuisine",
      tabItinerary: "Itinerary",
      tabPhrases: "Audio Phrases",
      tabTransport: "Transport",
      tabQuiz: "Travel Quiz",
      attractionsTitle: "Must-Visit Top Attractions",
      attractionsSub: "Showing curated spots in Andong",
      cuisineTitle: "Authentic Andong Delicacies",
      cuisineSub: "From savory braised chicken to historic scholar bibimbap and famous traditional spirits.",
      itineraryPresetTitle: "Recommended Itineraries",
      itineraryCustomTitle: "My Custom Trip Plan",
      itineraryEmptyTitle: "Your trip plan is empty!",
      itineraryEmptySub: "Click '+ Plan' on any attraction card to add it here.",
      phrasesTitle: "Essential Tourist Phrases",
      taxiBannerTitle: "Korean Audio & Taxi Cards",
      taxiBannerSub: "Tap the speaker button to hear native Korean audio playback using built-in speech synthesis!",
      transportTitle: "Transportation & Travel Tips",
      transportSub: "Everything you need to navigate Andong smoothly from Seoul or Busan.",
      emergencyTitle: "Emergency & Helpline Contacts",
      quizTitle: "Find Your Andong Travel Vibe",
      quizSub: "Answer 2 quick questions to get personalized spot recommendations.",
      btnDetails: "Details",
      btnPlan: "Plan",
      btnAddPlan: "+ Add to My Itinerary",
      btnPronounce: "Pronounce Name",
      showTaxiTitle: "Show To Taxi Driver",
      addressLabel: "Address:",
      hoursLabel: "Opening Hours:",
      feeLabel: "Admission:",
      transportLabel: "Bus & Transport:",
      whereToEatLabel: "Recommended Area:",
      priceLabel: "Est. Price:",
      footerText: "Discover Andong - International Tourist Guide & Digital Companion",
      cityHallBtn: "City Hall"
    },
    ko: {
      siteTitle: "안동 여행 가이드",
      siteSubtitle: "한국",
      heroTitle: "한국의 정신문화의 수도, 안동을 만나보세요",
      heroDesc: "유네스코 세계유산, 깊은 조선시대 전통 문화, 안동의 명물 먹거리를 안내하는 디지털 가이드입니다.",
      searchPlaceholder: "관광지 검색 (예: 하회마을, 찜닭, 월영교)...",
      searchBtn: "검색",
      filterAll: "전체 명소",
      filterHeritage: "유네스코 유산",
      filterNight: "야경 명소",
      filterKdrama: "K-드라마 촬영지",
      filterNature: "자연 및 공원",
      tabAttractions: "관광 명소",
      tabFood: "대표 먹거리",
      tabItinerary: "여행 코스",
      tabPhrases: "여행 한국어",
      tabTransport: "교통 안내",
      tabQuiz: "여행 취향 퀴즈",
      attractionsTitle: "안동 추천 명소",
      attractionsSub: "안동의 대표 관광지 목록입니다",
      cuisineTitle: "안동의 맛과 미식",
      cuisineSub: "안동 찜닭부터 종가집 헛제삿밥, 전통 안동소주까지 다양하게 즐겨보세요.",
      itineraryPresetTitle: "추천 여행 코스",
      itineraryCustomTitle: "나만의 여행 일정",
      itineraryEmptyTitle: "여행 일정이 비어있습니다!",
      itineraryEmptySub: "관광지 카드의 '+ 일정추가' 버튼을 눌러 나만의 코스를 만들어보세요.",
      phrasesTitle: "필수 여행 표현",
      taxiBannerTitle: "음성 발음 및 택시 전달 카드",
      taxiBannerSub: "스피커 버튼을 누르면 원어민 한국어 음성 발음을 들으실 수 있습니다!",
      transportTitle: "교통 및 대중교통 가이드",
      transportSub: "서울/부산에서 안동까지 편리하게 이동하는 방법입니다.",
      emergencyTitle: "비상 연락처 및 안내 핫라인",
      quizTitle: "나의 안동 여행 취향 찾기",
      quizSub: "2가지 질문에 답하고 나에게 꼭 맞는 관광지를 추천받아보세요.",
      btnDetails: "상세 보기",
      btnPlan: "일정추가",
      btnAddPlan: "+ 내 일정에 추가",
      btnPronounce: "명칭 발음 듣기",
      showTaxiTitle: "택시 기사님께 보여주세요",
      addressLabel: "주소:",
      hoursLabel: "운영 시간:",
      feeLabel: "입장료:",
      transportLabel: "교통 편:",
      whereToEatLabel: "추천 장소:",
      priceLabel: "예상 가격:",
      footerText: "Discover Andong - 안동 관광 종합 디지털 가이드",
      cityHallBtn: "안동시청"
    }
  },

  attractions: [
    {
      id: 'hahoe-village',
      name: 'Andong Hahoe Folk Village',
      nameKo: '안동 하회마을',
      category: 'heritage',
      tags: ['UNESCO', 'Culture', 'Hanok', 'Must-Visit'],
      image: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?auto=format&fit=crop&w=800&q=80',
      shortDesc: 'A historic UNESCO World Heritage village preserving Joseon-era Hanok architecture and clan traditions surrounded by Nakdong River.',
      shortDescKo: '낙동강이 S자로 감싸안은 조선 시대 풍산 류씨 씨족 마을이자 유네스코 세계유산입니다.',
      fullDesc: 'Hahoe Folk Village is one of South Korea\'s most famous historic clan villages. The name "Hahoe" means "river wrapping around," referring to the Nakdong River that bends around the S-shaped village. Homes here range from noble tile-roofed houses (Yangban) to thatched-roof cottages of commoners, all standing in their original condition.',
      fullDescKo: '하회마을은 한국의 대표적인 역사적 씨족 마을입니다. 마을 이름인 "하회"는 낙동강 물줄기가 마을을 S자로 감싸 흐른다는 데서 유래했습니다. 조선 시대 양반 가옥인 기와집과 서민들의 초가집이 원형 그대로 보존되어 있습니다.',
      location: '40 Hahoenam-gil, Pungcheon-myeon, Andong-si',
      locationKo: '경상북도 안동시 풍천면 하회남길 40',
      hours: '09:00 - 17:30 (Winter) / 09:00 - 18:00 (Summer)',
      hoursKo: '09:00 - 17:30 (동절기) / 09:00 - 18:00 (하절기)',
      fee: 'Adults 5,000 KRW / Youths 2,500 KRW',
      feeKo: '성인 5,000원 / 청소년 2,500원',
      transport: 'Take Bus #210 from Andong Station / Bus Terminal (approx. 45 mins)',
      transportKo: '안동역/버스터미널에서 210번 시내버스 이용 (약 45분 소요)',
      rating: 4.9,
      reviewsCount: 1280,
      taxiCardNote: '기사님, 하회마을 매표소로 가주세요.'
    },
    {
      id: 'byeongsan-seowon',
      name: 'Byeongsan Seowon Academy',
      nameKo: '병산서원',
      category: 'heritage',
      tags: ['UNESCO', 'Architecture', 'Nature', 'Quiet'],
      image: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?auto=format&fit=crop&w=800&q=80',
      shortDesc: 'Considered a masterpiece of Korean pavilion architecture with sweeping views of Nakdong River and cliff sides.',
      shortDescKo: '만휴정과 함께 안동을 대표하는 유네스코 서원 건축의 백미이자 탁 트인 절경을 자랑합니다.',
      fullDesc: 'Byeongsan Seowon is a Neo-Confucian academy established in honor of Ryu Seong-ryong. The open pavilion Mandaeru offers breathtaking unobstructed views of Mount Byeongsan across the river, perfectly integrating human architecture with wild nature.',
      fullDescKo: '병산서원은 서애 류성룡 선생의 업적을 기리기 위해 세워진 유학 교육기관입니다. 7칸 크기의 만대루에서 바라보는 병산과 낙동강의 탁 트인 풍경은 한국 서원 건축 중 으뜸으로 꼽힙니다.',
      location: '386 Byeongsan-gil, Pungcheon-myeon, Andong-si',
      locationKo: '경상북도 안동시 풍천면 병산길 386',
      hours: '09:00 - 18:00 (Daily, Free Entry)',
      hoursKo: '09:00 - 18:00 (매일, 무료 입장)',
      fee: 'Free Entrance',
      feeKo: '무료 관람',
      transport: 'Take Bus #210 (runs to Byeongsan Seowon 3 times daily) or 10 min taxi from Hahoe Village',
      transportKo: '210번 버스(1일 3회 경유) 또는 하회마을에서 택시로 10분 소요',
      rating: 4.8,
      reviewsCount: 850,
      taxiCardNote: '기사님, 병산서원으로 가주세요.'
    },
    {
      id: 'wollyeonggyo',
      name: 'Wollyeonggyo (Moonlight Bridge)',
      nameKo: '월영교',
      category: 'night',
      tags: ['Night View', 'Romance', 'Photo Spot', 'Must-Visit'],
      image: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=800&q=80',
      shortDesc: 'Korea\'s longest wooden footbridge, lit up beautifully at night over the tranquil Andong Lake.',
      shortDescKo: '안동호 위를横斷하는 국내 최대 규모의 목책 인도교로 아름다운 야경과 분수를 자랑합니다.',
      fullDesc: 'Wollyeonggyo spans 387 meters across Nakdong River / Andong Lake. It was built honoring a touching true love story from the 16th century between a wife and her deceased husband (Won-i\'s mother). Fountain shows operate periodically on weekends.',
      fullDescKo: '월영교는 길이 387m, 너비 3.6m의 국내에서 가장 긴 목조 인도교입니다. 16세기 숭고한 사랑을 고이 간직한 원이 엄마의 미투리(짚신) 모양을 형상화하였으며 밤이면 아름다운 경관조명이 켜집니다.',
      location: 'Sujong-ro, Seonggok-dong, Andong-si',
      locationKo: '경상북도 안동시 상아동 569 (월영교)',
      hours: 'Open 24 Hours (Lighting: Dusk to 22:00)',
      hoursKo: '24시간 상시 개방 (야간 조명: 일몰 후 ~ 22:00)',
      fee: 'Free Entrance',
      feeKo: '무료 관람',
      transport: 'Bus #112 or short 10-minute taxi from downtown Andong',
      transportKo: '112번 시내버스 또는 안동 시내에서 택시 10분 소요',
      rating: 4.9,
      reviewsCount: 2100,
      taxiCardNote: '기사님, 월영교 주차장으로 가주세요.'
    },
    {
      id: 'dosan-seowon',
      name: 'Dosan Seowon Academy',
      nameKo: '도산서원',
      category: 'heritage',
      tags: ['UNESCO', 'History', 'Scenic', 'Yi Hwang'],
      image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
      shortDesc: 'Established in 1574 by disciples of Korea\'s most revered Confucian scholar, Yi Hwang (pictured on the 1,000 KRW bill).',
      shortDescKo: '퇴계 이황 선생의 학문과 덕행을 기리기 위해 설립된 조선 시대 명문 서원입니다.',
      fullDesc: 'Dosan Seowon sits nestled in a tranquil pine forest overlooking the lake. The academy retains scholar lecture halls, student dormitories, and library buildings surrounded by lush trees and serene waters.',
      fullDescKo: '도산서원은 퇴계 이황 선생이 제자들을 가르치던 도산서당을 모태로 사후 제자들과 유림에 의해 건립되었습니다. 울창한 소나무 숲과 안동호가 어우러져 고즈넉한 학문의 정취를 전합니다.',
      location: '154 Dosanseowon-gil, Dosan-myeon, Andong-si',
      locationKo: '경상북도 안동시 도산면 도산서원길 154',
      hours: '09:00 - 18:00 (Summer) / 09:00 - 17:00 (Winter)',
      hoursKo: '09:00 - 18:00 (하절기) / 09:00 - 17:00 (동절기)',
      fee: 'Adults 2,000 KRW / Students 1,000 KRW',
      feeKo: '성인 2,000원 / 청소년 1,000원',
      transport: 'Take Bus #512 from Andong Station (~50 mins)',
      transportKo: '안동역에서 512번 버스 탑승 (약 50분 소요)',
      rating: 4.7,
      reviewsCount: 920,
      taxiCardNote: '기사님, 도산서원으로 가주세요.'
    },
    {
      id: 'manhyujeong',
      name: 'Manhyujeong Pavilion',
      nameKo: '만휴정',
      category: 'kdrama',
      tags: ['K-Drama', 'Mr. Sunshine', 'Photo Spot', 'Nature'],
      image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
      shortDesc: 'Iconic wooden bridge over a cascading stream, made world-famous by the hit Netflix K-Drama "Mr. Sunshine".',
      shortDescKo: '드라마 <미스터 션샤인>의 "합시다, 러브" 명대사 배경이 된 외나무다리 명소입니다.',
      fullDesc: '"Let\'s do it together. Love." This romantic location featured the famous scene between Eugene Choi and Go Ae-shin in Mr. Sunshine. Built in 1500 by scholar Kim Kye-haeng, it offers a peaceful retreat into nature with stream waterfalls and pine forest trails.',
      fullDescKo: '조선시대 문신 김계행 선생이 노년에 휴식을 취하기 위해 지은 정자입니다. 정자 앞 계곡을 건너는 외나무다리는 인스타그램 인생사진 명소로 유명합니다.',
      location: '42 Mukgye-gil, Gilan-myeon, Andong-si',
      locationKo: '경상북도 안동시 길안면 묵계길 42',
      hours: '09:30 - 18:00',
      hoursKo: '09:30 - 18:00',
      fee: 'Adults 2,000 KRW',
      feeKo: '성인 2,000원 (환경관리비)',
      transport: 'Bus #610 or taxi (approx 30 min ride from downtown)',
      transportKo: '610번 버스 또는 시내에서 택시 30분 소요',
      rating: 4.8,
      reviewsCount: 1540,
      taxiCardNote: '기사님, 미스터 션샤인 촬영지 만휴정으로 가주세요.'
    },
    {
      id: 'nakgang-water-park',
      name: 'Nakgang Water Garden (Secret Garden)',
      nameKo: '낙강물길공원',
      category: 'nature',
      tags: ['Nature', 'Secret Spot', 'Picnic', 'Photo Spot'],
      image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
      shortDesc: 'Nicknamed "Korea\'s Monet Garden", featuring serene pond reflections, stepping stones, and cozy forest benches.',
      shortDescKo: '한국의 지베르니(모네의 정원)라 불리며 버드나무와 돌다리가 연출하는 이국적 풍경을 자랑합니다.',
      fullDesc: 'Located right next to Andong Dam, Nakgang Water Garden is famous for its fairy-tale atmosphere with weeping willows, stepping stones across turquoise water streams, and mist fountains. Perfect for memorable travel photos!',
      fullDescKo: '안동댐 입구에 위치한 비밀의 정원으로 연못과 징검다리, 분수가 어우러져 그림 같은 사진을 남길 수 있는 곳입니다.',
      location: '423 Sang-a-dong, Andong-si',
      locationKo: '경상북도 안동시 상아동 423',
      hours: 'Open 24 hours',
      hoursKo: '24시간 상시 개방',
      fee: 'Free Entrance',
      feeKo: '무료 관람',
      transport: 'Walking distance (15 mins) from Wollyeonggyo Bridge or taxi',
      transportKo: '월영교에서 도보 15분 또는 택시이동',
      rating: 4.8,
      reviewsCount: 760,
      taxiCardNote: '기사님, 낙강물길공원으로 가주세요.'
    }
  ],

  foods: [
    {
      id: 'andong-jjimdak',
      name: 'Andong Jjimdak (Braised Chicken)',
      nameKo: '안동찜닭',
      category: 'Main Dish',
      spiciness: 'Medium (Can request mild)',
      spicinessKo: '보통 매운맛 (순한맛 요청 가능)',
      image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      desc: 'Andong’s signature dish: tender chicken, glass noodles, potatoes, carrots, and spicy chili peppers simmered in a savory soy-based sauce.',
      descKo: '닭고기에 쫄깃한 당면, 감자, 당근, 청양고추를 넣어 매콤달콤한 간장 양념으로 자작하게 조려낸 안동의 대표 대표 명물 요리입니다.',
      whereToEat: 'Andong Old Market Jjimdak Street (안동구시장 찜닭골목)',
      whereToEatKo: '안동구시장 찜닭골목',
      avgPrice: '28,000 ~ 32,000 KRW (Serves 2-3 people)',
      avgPriceKo: '28,000 ~ 32,000원 (2-3인분)',
      tips: 'Always order with extra chewy glass noodles! Pair with fresh radish kimchi.',
      tipsKo: '당면을 푸짐하게 드시는 것을 추천합니다! 치킨무나 동치미와 궁합이 매우 좋습니다.'
    },
    {
      id: 'gangeodeongeow',
      name: 'Gangeodeong-eo (Salt-Cured Mackerel)',
      nameKo: '안동 간고등어',
      category: 'Seafood Set Menu',
      spiciness: 'Non-spicy',
      spicinessKo: '순한맛 (안매움)',
      image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      desc: 'Salt-salted grilled mackerel with crispy skin and juicy rich flavor. Transported inland historically, salting created an uniquely deep savory taste.',
      descKo: '내륙지방인 안동으로 고등어를 수송하기 위해 염장(간하기)을 한 데서 유래하여, 짭조름하고 겉은 바삭 속은 촉촉한 맛이 특징입니다.',
      whereToEat: 'Iljik Shikdang (일직식당 near Andong Station)',
      whereToEatKo: '안동역 앞 일직식당 등',
      avgPrice: '12,000 ~ 15,000 KRW per person',
      avgPriceKo: '1인분 12,000 ~ 15,000원',
      tips: 'Comes as a full Han-jeongsik set with steamed rice, soybean paste stew (doenjang-jjigae), and side dishes.',
      tipsKo: '따끈한 쌀밥과 구수한 된장찌개, 각종 반찬이 함께 제공되는 한상차림으로 드세요.'
    },
    {
      id: 'heotjesatbap',
      name: 'Heotjesatbap (Fake Memorial Meal)',
      nameKo: '헛제삿밥',
      category: 'Bibimbap Style',
      spiciness: 'Non-spicy',
      spicinessKo: '순한맛 (안매움)',
      image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=800&q=80',
      desc: 'A non-spicy bibimbap originally eaten by Joseon scholars who pretended to hold ancestral rituals just to feast on delicious food late at night!',
      descKo: '제사를 지내지 않고도 제사 음식처럼 탕국과 전, 나물을 곁들여 고추장 대신 간장으로 비벼 먹는 유생들의 지혜가 담긴 전통 음식입니다.',
      whereToEat: 'Matnadang or Kkachi Tumeori near Wollyeonggyo Bridge',
      whereToEatKo: '월영교 인근 맛나당, 까치구멍집 등',
      avgPrice: '13,000 ~ 18,000 KRW',
      avgPriceKo: '13,000 ~ 18,000원',
      tips: 'Mixed with soy sauce instead of gochujang chili paste, highlighting natural vegetable flavors.',
      tipsKo: '고추장이 아닌 양념간장으로 비벼 고소하고 담백한 나물 본연의 맛을 느낄 수 있습니다.'
    },
    {
      id: 'andong-soju',
      name: 'Traditional Andong Soju (45% ABV)',
      nameKo: '안동 전통 소주',
      category: 'Traditional Liquor',
      spiciness: 'Strong Spirit',
      spicinessKo: '증류식 전통주 (45도)',
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
      desc: 'A legendary distilled rice spirit dating back to the Goryeo Dynasty (13th Century). Crisp, smooth, with a subtle floral aroma despite high ABV.',
      descKo: '고려시대부터 전해 내려온 100% 쌀과 전통 누룩으로 빚은 증류식 소주로, 높은 도수에도 은은한 향과 깔끔한 목넘김을 자랑합니다.',
      whereToEat: 'Andong Soju Museum & Traditional Liquor Shops',
      whereToEatKo: '안동소주 박물관 및 시내 전통주 매장',
      avgPrice: '10,000 ~ 35,000 KRW per bottle',
      avgPriceKo: '병당 10,000 ~ 35,000원',
      tips: 'Tastes smoothest served slightly chilled or over a single ice cube.',
      tipsKo: '살짝 차갑게 마시거나 얼음을 띄워 온더락으로 즐기시면 부드러움을 극대화할 수 있습니다.'
    }
  ],

  itineraries: [
    {
      id: 'express-1day',
      title: '1-Day Highlights Tour (Essential Andong)',
      titleKo: '1일 안동 하이라이트 핵심 코스',
      tag: 'Best for Short Visits',
      tagKo: '당일치기 추천',
      duration: '1 Day (~8 Hours)',
      durationKo: '1일 (약 8시간)',
      highlights: ['Hahoe Folk Village', 'Jjimdak Street', 'Wollyeonggyo Night View'],
      highlightsKo: ['하회마을', '찜닭골목', '월영교 야경'],
      schedule: [
        { time: '09:30', title: 'Arrival at Andong KTX Station', titleKo: '안동 KTX역 도착', detail: 'Store luggage or check in', detailKo: '짐보관 및 이동 준비' },
        { time: '10:30', title: 'Hahoe Folk Village Exploration', titleKo: '하회마을 관람', detail: 'Walk through historic Hanok alleys and river cliff views', detailKo: '고즈넉한 한옥 고택 골목 산책 및 부용대 조망' },
        { time: '13:00', title: 'Lunch: Andong Jjimdak', titleKo: '점심: 안동 찜닭', detail: 'Visit Old Market Jjimdak Alley for savory braised chicken', detailKo: '안동구시장 찜닭골목에서 푸짐한 점심 식사' },
        { time: '15:00', title: 'Byeongsan Seowon Academy', titleKo: '병산서원 관람', detail: 'Admire Mandaeru pavilion and surrounding nature', detailKo: '만대루에 올라 바라보는 낙동강과 병산의 절경 감상' },
        { time: '18:00', title: 'Dinner: Salted Mackerel', titleKo: '저녁: 간고등어 정식', detail: 'Enjoy traditional grilled fish set menu', detailKo: '노릇노릇한 간고등어 구이 정식 한상 차림' },
        { time: '19:30', title: 'Wollyeonggyo Moonlight Bridge', titleKo: '월영교 야경 산책', detail: 'Evening romantic walk on illuminated wooden bridge', detailKo: '은은한 조명이 켜진 국내 최장 목책교 산책' }
      ]
    },
    {
      id: 'cultural-2day',
      title: '2-Day UNESCO & K-Drama Deep Dive',
      titleKo: '2일 유네스코 유산 & K-드라마 힐링 코스',
      tag: 'Recommended Pace',
      tagKo: '1박 2일 정석 코스',
      duration: '2 Days 1 Night',
      durationKo: '1박 2일',
      highlights: ['Hahoe Mask Dance', 'Dosan Seowon', 'Manhyujeong Mr. Sunshine', 'Hanok Stay'],
      highlightsKo: ['하회탈춤 공연', '도산서원', '만휴정', '한옥 체험'],
      schedule: [
        { time: 'Day 1 - 10:00', title: 'Hahoe Village & Mask Dance Performance', titleKo: '하회마을 & 하회별신굿탈놀이', detail: 'Watch traditional Byeolsingut Talnori at 14:00', detailKo: '오후 2시 상설 탈춤 공연 관람' },
        { time: 'Day 1 - 18:00', title: 'Hanok Overnight Stay', titleKo: '한옥 고택 숙박 체험', detail: 'Experience sleeping in a traditional heated Ondol Hanok house', detailKo: '따뜻한 온돌방과 고택의 밤 정취 체험' },
        { time: 'Day 2 - 10:00', title: 'Manhyujeong Pavilion', titleKo: '만휴정 외나무다리', detail: 'Recreate scenes from K-Drama Mr. Sunshine on the stream bridge', detailKo: '미스터 션샤인 명장면 포토존에서 인생샷 남기기' },
        { time: 'Day 2 - 13:00', title: 'Heotjesatbap Lunch', titleKo: '점심: 헛제삿밥', detail: 'Taste scholar-style non-spicy memorial bibimbap', detailKo: '담백하고 구수한 정갈한 한상차림' },
        { time: 'Day 2 - 15:30', title: 'Dosan Seowon Confucian Academy', titleKo: '도산서원 관람', detail: 'Explore scholar libraries on the hillside lake', detailKo: '퇴계 이황 선생의 학문 정취와 안동호 풍경 관람' }
      ]
    }
  ],

  phrases: [
    {
      english: "Hello / Good day",
      hangeul: "안녕하세요",
      romanized: "An-nyeong-ha-se-yo",
      audioText: "안녕하세요"
    },
    {
      english: "Thank you very much",
      hangeul: "감사합니다",
      romanized: "Gam-sa-ham-ni-da",
      audioText: "감사합니다"
    },
    {
      english: "Please take me to Hahoe Village",
      hangeul: "하회마을로 가주세요",
      romanized: "Ha-hoe-ma-eul-ro ga-ju-se-yo",
      audioText: "하회마을로 가주세요"
    },
    {
      english: "Is this dish spicy?",
      hangeul: "이 음식 매워요?",
      romanized: "I eum-sik mae-wo-yo?",
      audioText: "이 음식 매워요?"
    },
    {
      english: "Please make it less spicy",
      hangeul: "덜 매운 맛으로 해주세요",
      romanized: "Deol mae-un mas-eu-ro hae-ju-se-yo",
      audioText: "덜 매운 맛으로 해주세요"
    },
    {
      english: "Where is the bus stop?",
      hangeul: "버스 정류장이 어디예요?",
      romanized: "Beo-seu jeong-ryu-jang-i eo-di-ye-yo?",
      audioText: "버스 정류장이 어디예요?"
    },
    {
      english: "Can I pay by credit card?",
      hangeul: "카드 결제 되나요?",
      romanized: "Ka-deu gyeol-je doe-na-yo?",
      audioText: "카드 결제 되나요?"
    }
  ],

  transportGuide: [
    {
      title: 'KTX-Eum High-Speed Train (Seoul to Andong)',
      titleKo: 'KTX-이음 고속열차 (서울 ~ 안동)',
      details: 'Departs from Seoul Cheongnyangni Station or Yeongdeungpo. Reaches Andong Station in just 2 hours! Train tickets can be booked online via Let\'s Korail.',
      detailsKo: '청량리역 또는 영등포역에서 출발하여 2시간 만에 안동역에 도착합니다. 코레일 홈페이지 및 승차권 앱에서 예매하실 수 있습니다.'
    },
    {
      title: 'City Bus #210 (To Hahoe Village & Byeongsan)',
      titleKo: '210번 시내버스 (하회마을 & 병산서원)',
      details: 'Bus #210 connects Andong KTX Station, Bus Terminal, and Downtown to Hahoe Folk Village. Departs every 30-40 minutes. Accepts T-Money / Credit Card.',
      detailsKo: '안동 KTX역, 버스터미널, 시내에서 하회마을까지 이동하는 대표 버스입니다. 30~40분 간격 운행하며 교통카드 사용이 가능합니다.'
    },
    {
      title: 'Taxi & Kakao T App Tips',
      titleKo: '택시 이용 및 카카오 T 앱 활용',
      details: 'Taxis are plentiful around Andong Station. Download Kakao T app for easy taxi hail with predefined destinations. Base taxi fare starts at 4,000 KRW.',
      detailsKo: '안동역 및 터미널 전면에 택시 승강장이 있으며, 카카오 T 앱으로 편리하게 택시를 호출할 수 있습니다. 기본요금은 4,000원입니다.'
    },
    {
      title: 'Tourist Helpline 1330',
      titleKo: '관광통역안내전화 1330',
      details: 'Free 24/7 travel assistance in English, Chinese, Japanese, and Russian. Dial 1330 from any mobile phone in Korea or call via KakaoTalk.',
      detailsKo: '국번없이 1330번으로 전화하시면 24시간 한국어, 영어, 중국어, 일어 관광 안내 및 통역 서비스를 무료로 이용하실 수 있습니다.'
    }
  ]
};
